import os
import json
from groq import AsyncGroq
from dotenv import load_dotenv

load_dotenv()

client = AsyncGroq(
    api_key=os.getenv("GROQ_API_KEY")
)

async def get_ai_feedback(topic: str, question: str, student_answer: str, correct_answer: str, is_correct: bool) -> str:
    """
    Sends a prompt to Groq AI to generate personalized feedback based on the student's answer.
    """
    
    # Building the prompt
    if is_correct:
        prompt = (
            f"A student is studying {topic}. They were asked: '{question}'. "
            f"They correctly answered: '{student_answer}'. "
            f"Act as a supportive teacher. Briefly congratulate them, and provide a short, "
            f"interesting follow-up fact to keep them motivated and challenged."
        )
    else:
        prompt = (
            f"A student is studying {topic}. They were asked: '{question}'. "
            f"They answered: '{student_answer}', but the correct answer is '{correct_answer}'. "
            f"Act as a supportive teacher. Do not just say 'wrong'. Gently explain why their "
            f"answer was incorrect, and teach them the correct concept in a simple, beginner-friendly way."
        )

    # Call the Groq API
    try:
        
        response = await client.chat.completions.create(
            messages=[
                {
                    "role": "user",
                    "content": prompt,
                }
            ],
            model="llama-3.3-70b-versatile", 
            temperature=0.7, 
            max_tokens=500 
        )
        
        # Return the text generated by the AI
        return response.choices[0].message.content

    except Exception as e:
        print(f"Error calling Groq API: {e}")
        return "Your answer was recorded, but we couldn't generate AI feedback at this time."
    
async def generate_question(topic: str, difficulty: str) -> dict:
    """
    Asks Groq to generate a new quiz question and returns it as a dictionary.
    """
    prompt = (
        f"Generate one {difficulty} level quiz question about {topic}. "
        "You must respond ONLY with a valid JSON object in this exact format: "
        '{"question": "The question text", "correct_answer": "The answer text"}'
    )

    try:
        response = await client.chat.completions.create(
            messages=[{"role": "user", "content": prompt}],
            model="llama-3.3-70b-versatile",
            temperature=0.7,
            max_tokens=200,
            response_format={"type": "json_object"} 
        )
        
        response_text = response.choices[0].message.content
        return json.loads(response_text)

    except Exception as e:
        print(f"Error generating question: {e}")
        return {"error": "Could not generate question"}